language: node_js

node_js:
  - 10.7.0

install:
  - npm install -g firebase-tools
  - npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
    - master

script:
  - npm run build
  - echo "Deploy"

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
